---
title: "Spatial Viz"
---

Use this file to generate a professional looking **spatial** visualization.  The visualization will not be perfect the first time but you are expected to improve on it throughout the semester especially after covering advanced topics such as effective viz.

```{r}
# Load packages
library(tidyverse)
library(openintro)
library(ggthemes)
library(viridis)
library(leaflet)
library(gplots)
```

```{r}
# Import starbucks location data
starbucks <- read.csv("https://mac-stat.github.io/data/starbucks.csv")

# Keep only stores in contiguous US
starbucks_us <- starbucks |>
  filter(Country == "US", !State.Province %in% c("AK", "HI"))

# Create the dataset `starbucks_us_by_state` that gives the number of Starbucks in each state. 
starbucks_us_by_state <- starbucks_us |>
  count(State.Province) |>
  mutate(state_name = str_to_lower(abbr2state(State.Province)))

# Import census data
census_pop_est_2018 <- read_csv("https://mac-stat.github.io/data/us_census_2018_state_pop_est.csv") |>
  separate(state, into = c("dot", "state"), extra = "merge") |>
  select(-dot) |>
  mutate(state = str_to_lower(state))

# Add variable "starbucks_per_10000"
starbucks_with_2018_pop_est <-
  starbucks_us_by_state |>
  left_join(census_pop_est_2018,
    by = c("state_name" = "state")
  ) |>
  mutate(starbucks_per_10000 = (n / est_pop_2018) * 10000)

# limiting data points to contiguous US
starbucks_contiguous_us <- starbucks |>
  filter(Country == "US", State.Province != "AK", State.Province != "HI")

# Get the latitude and longitude coordinates of state boundaries
states_map <- map_data("state")
```

```{r}
#| fig-cap: "Created by Dust L. for COMP112 at Macalester College. Data from [GitHub](https://mac-stat.github.io/data/starbucks.csv)."
#| fig-alt: "Chloropleth Map of Starbucks density in the contiguous United States, per 10,000 people. Starbucks locations are marked with black points on the map."
#| fig-width: 8
#| fig-height: 5

ggplot(starbucks_with_2018_pop_est, aes(map_id = state_name, fill = starbucks_per_10000)) +
  geom_map(map = states_map) +
  geom_point(
    data = starbucks_contiguous_us,
    aes(x = Longitude, y = Latitude),
    size = 0.05,
    alpha = 0.2,
    inherit.aes = FALSE,
    color = "black"
  ) +
  expand_limits(x = states_map$long, y = states_map$lat) +
  theme_map() +
  theme(legend.title = element_text(size = 6), title = element_text(size = 14)) + 
  scale_fill_viridis(option = "viridis", direction = -1) +
  labs(title = "Starbucks Density by Population in the Contiguous US", fill = "Starbucks per 10,000 people")
```
