---
title: "Exam 1"
number-sections: false
---
```{r}
library(tidytuesdayR)
library(tidyverse)
```

```{r}
# data import
tuesdata <- tt_load("2020-02-18")
fc <- tuesdata$food_consumption

# examine the data
names(fc)
nrow(fc)
ncol(fc)
str(fc)

head(fc, 22)
tail(fc, 22)
```

```{r}
# understanding variables individually
# the RQ involves 3 variables: consumption, food category, country

# consumption (quantitative)
ggplot(fc, aes(x = consumption)) + 
  geom_density()
```
```{r}
# understanding consumption
# moving from uni into bivar viz

# consumption (quantitative) / food category (categorical)
ggplot(fc, aes(y = consumption)) + 
  geom_histogram() + 
  facet_wrap(~food_category)
```


```{r}
#| fig-height: 22
#| fig-width: 11
# consumption (quantitative) / country (categorical)
ggplot(fc, aes(y = consumption)) + 
  geom_histogram(aes(fill = country))

ggplot(fc, aes(y = consumption, x = country)) + 
  geom_boxplot()
```
```{r}
#| fig-height: 22
#| fig-width: 11
# incorporating all three variables
ggplot(fc, aes(x = consumption)) + 
  geom_histogram(aes(fill = food_category)) + 
  facet_wrap(~country)
```
