---
title: "Effective Viz"
number-sections: false
---

- The big questions: effective - complete - accessible
- Everything you add to the graph must be **intentional**

## Exercise 1
```{r}
# Load tidyverse package for plotting and wrangling
library(tidyverse)

# Import the data
weather <- read.csv("https://mac-stat.github.io/data/weather_3_locations.csv") |> 
  mutate(date = as.Date(date))
```
```{r}
ggplot(weather, aes(y = temp3pm, x = temp9am, color = location)) + 
  geom_point()
```
### Part a:
```{r}
ggplot(weather, aes(y = temp3pm, x = temp9am, color = location)) + 
  geom_point() + 
  labs(x = "9am Temperature (F)", y = "3pm Temperature (F)", title = "Comparisons of Temperatures in Australia", color = "Location")  
```
### Part b:
```{r}
#| fig-cap: "This shows a comparison of temperatures at 9am vs. 3pm at three locations in Australia, in degrees Fahrenheit."

ggplot(weather, aes(y = temp3pm, x = temp9am, color = location)) + 
  geom_point() + 
  labs(x = "9am Temperature (F)", y = "3pm Temperature (F)", color = "Location")
```
## Exercise 2
```{r}
ggplot(weather, aes(x = temp3pm, fill = location)) + 
  geom_density(alpha = 0.5) + 
  labs(x = "3pm temperature (Celsius)")  
```

